/** Every label in the admin panel. Same rule as the landing: nothing inline in JSX. */
export const admin = {
  brand: 'ISISI',
  title: 'Admin',
  backToSite: 'Landing page',
  sample: 'Sample data · not connected',
  live: 'Live',
  range: { label: 'Range', options: [{ value: '24h', label: 'Last 24 h' }] },
  refresh: 'Refresh',
  refreshing: 'Refreshing…',
  tiles: {
    calls: 'Calls analysed',
    synthetic: 'Flagged synthetic',
    abstained: 'Abstained',
    latency: 'Median latency',
    latency95: 'p95 latency',
    decided: 'Median time to verdict',
    ofCalls: 'of calls',
    vsPrev: 'vs previous 24 h',
  },
  charts: {
    hourly: 'Verdicts by hour',
    hourlySub: 'Calls per hour, stacked by verdict',
    confidence: 'Confidence distribution',
    confidenceSub: 'All verdicts, 10 bins',
    latency: 'Latency p50',
    latencySub: '30-minute buckets, last 24 h',
    chart: 'Chart',
    table: 'Table',
    hour: 'Hour',
    bin: 'Confidence',
    calls: 'Calls',
    bucket: 'Bucket',
    ms: 'ms',
  },
  verdict: { human: 'Human', synthetic: 'Synthetic', abstained: 'Abstained' },
  trap: { refused: 'Refused', answered: 'Answered', none: 'No trap' },
  stream: {
    title: 'Calls',
    all: 'All',
    search: 'Search call id or queue',
    empty: 'No calls match.',
    cols: {
      time: 'Time', id: 'Call', queue: 'Queue', duration: 'Length', verdict: 'Verdict',
      confidence: 'Conf.', signals: 'Acoustic · Behaviour · Semantic', decided: 'Verdict at', latency: 'Latency', trap: 'Trap',
    },
    showing: 'Showing',
  },
  detail: {
    title: 'Call detail',
    pick: 'Select a call to see how the verdict was reached.',
    channels: 'Channels',
    stereo: 'Stereo · channel 0 classified',
    mono: 'Mono · behaviour layer abstains',
    confidence: 'Confidence',
    signals: { acoustic: 'Acoustic', conversational: 'Behaviour', semantic: 'Semantic' },
    decided: 'Decided at',
    notDecided: 'Not settled',
    latency: 'Latency',
    trap: 'Trap question',
    response: 'Response',
    review: 'Open in review',
    reviewNote: 'Review queue is not wired yet.',
    close: 'Close',
  },
  tester: {
    title: 'Try the endpoint',
    sub: 'POST /detect with a sample or your own file.',
    sample: 'Sample',
    samples: { human: 'Real caller', synthetic: 'Cloned voice' },
    file: 'Or upload a WAV',
    run: 'Analyse',
    running: 'Analysing…',
    request: 'Request',
    response: 'Response',
    took: 'Round trip',
    mockNote: 'Sample response. Nothing leaves the browser.',
    curl: 'curl',
  },
  health: {
    title: 'Endpoint',
    status: { up: 'Operational', degraded: 'Degraded', down: 'Down' },
    model: 'Model',
    calibrated: 'Calibrated',
    streaming: 'Streaming mode',
    on: 'On',
    off: 'Off',
    uptime: 'Uptime 24 h',
    queue: 'Queue depth',
    checked: 'Checked',
  },
}
