/** Every label in the admin panel. Same rule as the landing: nothing inline in JSX. */
export const admin = {
  brand: 'ISISI',
  title: 'Administración',
  backToSite: 'Página principal',
  sample: 'Datos de muestra · sin conexión',
  live: 'En vivo',
  range: { label: 'Rango', options: [{ value: '24h', label: 'Últimas 24 h' }] },
  refresh: 'Actualizar',
  refreshing: 'Actualizando…',
  tiles: {
    calls: 'Llamadas analizadas',
    synthetic: 'Marcadas como Synthetic',
    abstained: 'Abstenciones',
    latency: 'Latencia mediana',
    latency95: 'Latencia p95',
    decided: 'Tiempo mediano al veredicto',
    ofCalls: 'de las llamadas',
    vsPrev: 'vs 24 h previas',
  },
  charts: {
    hourly: 'Veredictos por hora',
    hourlySub: 'Llamadas por hora, apiladas por veredicto',
    confidence: 'Distribución de confianza',
    confidenceSub: 'Todos los veredictos, 10 rangos',
    latency: 'Latencia p50',
    latencySub: 'Bloques de 30 minutos, últimas 24 h',
    chart: 'Gráfica',
    table: 'Tabla',
    hour: 'Hora',
    bin: 'Confianza',
    calls: 'Llamadas',
    bucket: 'Bloque',
    ms: 'ms',
  },
  verdict: { human: 'Human', synthetic: 'Synthetic', abstained: 'Se abstuvo' },
  trap: { refused: 'Rechazó', answered: 'Respondió', none: 'Sin trampa' },
  stream: {
    title: 'Llamadas',
    all: 'Todas',
    search: 'Buscar id de llamada o cola',
    empty: 'Ninguna llamada coincide.',
    cols: {
      time: 'Hora', id: 'Llamada', queue: 'Cola', duration: 'Duración', verdict: 'Veredicto',
      confidence: 'Conf.', signals: 'Voz · Conversación · Contenido', decided: 'Veredicto en', latency: 'Latencia', trap: 'Trampa',
    },
    showing: 'Mostrando',
  },
  detail: {
    title: 'Detalle de la llamada',
    pick: 'Selecciona una llamada para ver cómo se llegó al veredicto.',
    channels: 'Canales',
    stereo: 'Estéreo · se clasifica el canal 0',
    mono: 'Mono · la capa de conversación se abstiene',
    confidence: 'Confianza',
    signals: { acoustic: 'Voz', conversational: 'Conversación', semantic: 'Contenido' },
    decided: 'Decidido en',
    notDecided: 'Sin resolver',
    latency: 'Latencia',
    trap: 'Pregunta trampa',
    response: 'Respuesta',
    review: 'Abrir en revisión',
    reviewNote: 'La cola de revisión aún no está conectada.',
    close: 'Cerrar',
  },
  tester: {
    title: 'Probar el endpoint',
    sub: 'POST /detect con una muestra o un archivo propio.',
    sample: 'Muestra',
    samples: { human: 'Llamante real', synthetic: 'Voz clonada' },
    file: 'O subir un WAV',
    run: 'Analizar',
    running: 'Analizando…',
    request: 'Petición',
    response: 'Respuesta',
    took: 'Ida y vuelta',
    mockNote: 'Respuesta de muestra. Nada sale del navegador.',
    curl: 'curl',
  },
  health: {
    title: 'Endpoint',
    status: { up: 'Operativo', degraded: 'Degradado', down: 'Caído' },
    model: 'Modelo',
    calibrated: 'Calibrado',
    streaming: 'Modo streaming',
    on: 'Activo',
    off: 'Inactivo',
    uptime: 'Disponibilidad 24 h',
    queue: 'Tamaño de la cola',
    checked: 'Última revisión',
  },
  telemetry: {
    title: 'Telemetría Tiger',
    sub: 'Cada veredicto, copiado a Tiger Data.',
    status: { up: 'Conectado', down: 'Sin respuesta', off: 'Sin configurar' },
    stored: 'Veredictos guardados',
    split: 'Synthetic / human',
    confidence: 'Confianza promedio',
    latency: 'Latencia promedio',
    last: 'Último evento',
    offNote: 'Define VITE_TELEMETRY_URL para leer el servicio desde aquí.',
    downNote: 'El servicio no respondió en la URL configurada.',
  },
}
